spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: msa
  data:
    mongodb:
      uri: mongodb://root:1234@localhost/order?authSource=admin


springbootwebfluxjjwt:
  password:
    encoder:
      secret: mysecret
      iteration: 33
      keylength: 256
  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
    expiration: 28800




threadPool:
  notification:
    event: 8