### 어드민 생성
POST http://localhost:18080/api/v1/admin
Content-Type: application/json
Authorization: Bearer {{giftAccessToken}}

{
  "loginId": "admin3",
  "password": "admin3"
}

### 다른 유저 정보 조회
GET http://localhost:18080/api/v1/admin/user
Content-Type: application/json
Authorization: Bearer {{giftAccessToken}}

### 다른 유저 탈퇴
PATCH http://localhost:18080/api/v1/admin/user/quit
Content-Type: application/json
Authorization: Bearer {{giftAccessToken}}

### 다른 유저 재가입
PATCH http://localhost:18080/api/v1/admin/user/come-back
Content-Type: application/json
Authorization: Bearer {{giftAccessToken}}