### 유저 생성
POST http://localhost:18080/api/v1/user
Content-Type: application/json

{
  "username": "user",
  "password": "user"
}

### 내 정보 조회
GET http://localhost:18080/api/v1/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbeyJyb2xlIjoiUk9MRV9VU0VSIn1dLCJzdWIiOiJ1c2VyIiwiaWF0IjoxNjQ2MjMyMzM4LCJleHAiOjE2NDYyNjExMzh9.5q9_6DQU-1mU1Hil-3KjKp9c-pK3_h1QCsaxP1Ujon_62c1-mHRSXcH5dvxzwkc7hV9j4aSuvzQzu_75Wkq19Q

### 회원 탈퇴
PATCH http://localhost:18080/api/v1/user/quit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiJdLCJzdWIiOiJ1c2VyIiwiaWF0IjoxNjQ2MTE1MDIyLCJleHAiOjE2NDYxNDM4MjJ9.z2obEsChGoVv6ChixLrJxCeFjA3tTsgYRfvGEkcr8BmOFLo2sLPMjtHDabXSOGmn4FXWVvrzOJtBpu0CpFN24w

### 회원 재가입
PATCH http://localhost:18080/api/v1/user/come-back
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiJdLCJzdWIiOiJ1c2VyIiwiaWF0IjoxNjQ2MTE1MDIyLCJleHAiOjE2NDYxNDM4MjJ9.z2obEsChGoVv6ChixLrJxCeFjA3tTsgYRfvGEkcr8BmOFLo2sLPMjtHDabXSOGmn4FXWVvrzOJtBpu0CpFN24w
