### 어드민 생성
POST http://localhost:8080/api/v1/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfQURNSU4iXSwic3ViIjoiYWRtaW4iLCJpYXQiOjE2NDYzNjk2MzcsImV4cCI6MTY0NjM5ODQzN30.9PB6YWB8W73tl2M5yKi5zKrNafb-Q6hpVOgdKpWfkg9KopmyddbFVI-HDikn8Lk-fUl9sjCXmBNlqB6QJm7_NQ

{
  "username": "admin4",
  "password": "admin4"
}

