### 파트너 인증
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "loginId": "partner7",
  "password": "partner7"
}

### 유저 인증
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "loginId": "user",
  "password": "user"
}

### 토큰 재발행
POST http://localhost:8080/api/v1/auth/reissue
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiJdLCJzdWIiOiJ1c2VyIiwiaWF0IjoxNjQ4MzYxNDM3LCJleHAiOjE2NDgzNjg2Mzd9.n5howEhfWSDutqQhb3ls4vVZ8yGLYDLuu4bd2-Ou5xuB_p1vXbrbOmMeMxLh4RkhkCoHWA0mvGfJhBearX4kVA",
  "refreshToken": "eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiJdLCJzdWIiOiJ1c2VyIiwiaWF0IjoxNjQ4MzU4ODk3LCJleHAiOjE2NDk1Njg0OTd9.nCgQW7TFhFLY_9HJ2g32OUlgpi0umgcNFGGU1nUluOgqqi7AZ5z2sq_jFmLu0L0xux765RC5hhW2qhoYuxXp-A"
}
