### 파트너 인증
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "loginId": "partner7",
  "password": "partner7"
}
> {%
 client.global.set("orderAccessToken", response.body.data.accessToken);
 client.global.set("orderRefreshToken", response.body.data.refreshToken);
 %}

### 유저 인증
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "loginId": "user",
  "password": "user"
}
> {%
 client.global.set("orderAccessToken", response.body.data.accessToken);
 client.global.set("orderRefreshToken", response.body.data.refreshToken);
 %}

### 어드민 인증
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "loginId": "admin",
  "password": "admin"
}
> {%
 client.global.set("orderAccessToken", response.body.data.accessToken);
 client.global.set("orderRefreshToken", response.body.data.refreshToken);
 %}

### 토큰 재발행
POST http://localhost:8080/api/v1/auth/reissue
Content-Type: application/json

{
  "accessToken": "{{orderAccessToken}}",
  "refreshToken": "{{orderRefreshToken}}"
}
> {%
 client.global.set("orderAccessToken", response.body.data.accessToken);
 client.global.set("orderRefreshToken", response.body.data.refreshToken);
 %}

### 로그아웃
POST http://localhost:8080/api/v1/auth/logout
Content-Type: application/json
Authorization: Bearer {{orderAccessToken}}