### 파트너 인증
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "loginId": "partner7",
  "password": "partner7"
}

### 유저 인증
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "loginId": "user",
  "password": "user"
}

### 토큰 재발행
POST http://localhost:8080/api/v1/auth/reissue
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfUEFSVE5FUiJdLCJzdWIiOiJwYXJ0bmVyNyIsImlhdCI6MTY0ODM5ODM3NCwiZXhwIjoxNjQ4NDA1NTc0fQ.Dcv8EpY2GLxzfgqTtH9Qslb1jXecpxqEbhzarqZCbaHUPghXvAv6vLxU0oZa8Iup9Rc_ySR_pQ551sMyCLxfKA",
  "refreshToken": "eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfUEFSVE5FUiJdLCJzdWIiOiJwYXJ0bmVyNyIsImlhdCI6MTY0ODM5ODM3NCwiZXhwIjoxNjQ5NjA3OTc0fQ.FzkD0hDuscaCY2196jhQdrbPubUTJPYWnWnvgCGBv4xX1L8vHHrKagH4mUo_7c_5nNSvUFH2hRMkqKx6y8wxAg"
}
