### 주문 요청 초기 저장
POST http://localhost:8080/api/v1/orders/init
Content-Type: application/json

{
  "userId": "12345",
  "payMethod": "NAVER_PAY",
  "receiverName": "이희창",
  "receiverPhone": "01000001234",
  "receiverZipcode": "12345",
  "receiverAddress1": "서울시 강동구",
  "receiverAddress2": "우리집",
  "etcMessage": "감사합니다",
  "orderItemList": [
    {
      "orderCount": 2,
      "itemToken": "itm_5e2OwXwjlaU1diDW",
      "itemName": "티셔츠",
      "itemPrice": "30000",
      "orderItemOptionGroupList": [
        {
          "ordering": 1,
          "itemOptionGroupName": "사이즈",
          "orderItemOptionList": [
            {
              "ordering": 1,
              "itemOptionName": "MEDIUM",
              "itemOptionPrice": 0
            }
          ]
        },
        {
          "ordering": 2,
          "itemOptionGroupName": "컬러",
          "orderItemOptionList": [
            {
              "ordering": 1,
              "itemOptionName": "GOLD",
              "itemOptionPrice": 1000
            }
          ]
        }
      ]
    },
    {
      "orderCount": 1,
      "itemToken": "itm_kAyI718RmReYl6IU",
      "itemName": "양말",
      "itemPrice": "10000",
      "orderItemOptionGroupList": [
        {
          "ordering": 1,
          "itemOptionGroupName": "사이즈",
          "orderItemOptionList": [
            {
              "ordering": 1,
              "itemOptionName": "LARGE",
              "itemOptionPrice": 0
            }
          ]
        },
        {
          "ordering": 2,
          "itemOptionGroupName": "컬러",
          "orderItemOptionList": [
            {
              "ordering": 1,
              "itemOptionName": "RED",
              "itemOptionPrice": 0
            }
          ]
        }
      ]
    }
  ]
}