### 파트너 등록
POST http://localhost:8080/api/v1/partners
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfQURNSU4iXSwic3ViIjoiYWRtaW4iLCJpYXQiOjE2NDY1ODAyODAsImV4cCI6MTY0NjYwOTA4MH0.cbP0LH0BnCdvl_Upr_ypr0iM8HRgmvSezSY6r45w40PzvpM9mjMfDV9WM2-AEgqKhhLhiXdl_tmRPdGfyPK9eg

{
  "user": {
    "loginId": "partner5",
    "password": "partner5"
  },
  "partnerName": "test5",
  "businessNo": "12341",
  "email": "greg.shiny8@gmail.com"
}