### 유저 생성
POST http://localhost:8080/api/v1/user
Content-Type: application/json

{
  "username": "user",
  "password": "user"
}

### 내 정보 조회
GET http://localhost:8080/api/v1/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiJdLCJzdWIiOiJ1c2VyIiwiaWF0IjoxNjQ2MTEzMjgzLCJleHAiOjE2NDYxNDIwODN9.Dmfl1i6ERloczQRzQrCHAoiutxMsqSMIVo-jWu_f4Q1YyjZ1IQbOfX_zHfxIVcZ-QDBadZUZpYUlaaveN2uUbA


### 회원 탈퇴
PATCH http://localhost:8080/api/v1/user/quit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiJdLCJzdWIiOiJ1c2VyIiwiaWF0IjoxNjQ2MTEzMjgzLCJleHAiOjE2NDYxNDIwODN9.Dmfl1i6ERloczQRzQrCHAoiutxMsqSMIVo-jWu_f4Q1YyjZ1IQbOfX_zHfxIVcZ-QDBadZUZpYUlaaveN2uUbA


### 회원 재가입
PATCH http://localhost:8080/api/v1/user/come-back
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiJdLCJzdWIiOiJ1c2VyIiwiaWF0IjoxNjQ2MTEzMjgzLCJleHAiOjE2NDYxNDIwODN9.Dmfl1i6ERloczQRzQrCHAoiutxMsqSMIVo-jWu_f4Q1YyjZ1IQbOfX_zHfxIVcZ-QDBadZUZpYUlaaveN2uUbA

